CREATE TABLE CLIENTES (
    CEDULA              NUMBER(38)    NOT NULL,
    NOMBRE              VARCHAR2(255 CHAR) NOT NULL,
    APELLIDO1           VARCHAR2(255 CHAR) NOT NULL,
    APELLIDO2           VARCHAR2(255 CHAR) NOT NULL,
    DIRECCION           VARCHAR2(255 CHAR),
    E_MAIL              VARCHAR2(255 CHAR),
    FECHA_INSCRIPCION   DATE,
    CELULAR             NUMBER(38),
    TEL_HABITACION      NUMBER(38),
    PASSWORD            VARCHAR2(255),
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CEDULA)
);

CREATE TABLE EMPLEADOS (
    CEDULA              NUMBER(38)    NOT NULL,
    NOMBRE              VARCHAR2(255 CHAR) NOT NULL,
    APELLIDO1           VARCHAR2(255 CHAR) NOT NULL,
    APELLIDO2           VARCHAR2(255 CHAR) NOT NULL,
    DIRECCION           VARCHAR2(255 CHAR),
    E_MAIL              VARCHAR2(255 CHAR),
    TEL_CEL             VARCHAR2(255 CHAR),
    TEL_HABITACION      VARCHAR2(255 CHAR),
    FECHA_CONTRATACION  DATE,
    PASSWORD            VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (CEDULA)
);


CREATE TABLE RUTINAS (
    ID_RUTINA   NUMBER(10)    NOT NULL,
    FECHA       TIMESTAMP(6),
    HORAS       NUMBER(10)    NOT NULL,
    NOMBRE      VARCHAR2(255 CHAR),
    CLIENTE     NUMBER(19),
    INSTRUCTOR  NUMBER(10),
    MAQUINA     NUMBER(10),
    CONSTRAINT PK_RUTINAS PRIMARY KEY (ID_RUTINA)
);


CREATE TABLE MAQUINAS (
    ID_MAQUINA   NUMBER(38)    NOT NULL,
    DESCRIPCION  VARCHAR2(255 CHAR),
    ESTADO       VARCHAR2(255 CHAR),
    CONSTRAINT PK_MAQUINAS PRIMARY KEY (ID_MAQUINA)
);
CREATE TABLE CURSOS (
    ID_CURSO    NUMBER(38)    NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    NOMBRE      VARCHAR2(255 CHAR),
    HORARIO     VARCHAR2(255 CHAR),
    CONSTRAINT PK_CURSOS PRIMARY KEY (ID_CURSO)
);

